#!/bin/bash

# Set decoration geometry
berryc border_width       5
berryc inner_border_width 3
berryc title_height       0
berryc top_gap            40

# Set decoration colors
berryc focus_color         ffffff
berryc unfocus_color       000000
berryc inner_focus_color   555555
berryc inner_unfocus_color 555555
berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeee

# Other options
berryc smart_place "true"
berryc draw_text   "false"
berryc edge_lock   "true"
berryc set_font    "JetBrains Mono Nerd Font-10"
